((:key-properties
  ("blb" :place :bilabial)
  ("lbd" :place :labiodental)
  ("dnt" :place :dental)
  ("alv" :place :alveolar)
  ("pla" :place :post-alveolar)
  ("rfx" :place :retroflex)
  ("pal" :place :palatal)
  ("lbv" :place :labio-velar)
  ("vel" :place :velar)
  ("uvl" :place :uvular)
  ("phr" :place :pharyngeal)
  ("glt" :place :glottal)
  ("stp" :manner :stop)
  ("nas" :manner :nasal)
  ("trl" :manner :trill)
  ("frc" :manner :fricative)
  ("apr" :manner :approximant)
  ("flp" :manner :flap)
  ("vls" :voice nil)
  ("vcd" :voice t)
  ("lat" :lateral-release t))
 (:additional-properties
  ("vel" :velarised t)
  ("pal" :palatalised t)))
